### PR TITLE
Merge GSoC 2015 into master

### PR DESCRIPTION
**Pull request by tschuy**
After this is merged, I'll cut a new release -- v1.5 or v2.0? and push to production.

### CODE REVIEW

**Comment by tschuy** [comment]
I don't know why this includes some commits from before January 29th that I'm pretty sure are in master already.

**Comment by iCHAIT** [comment]
@tschuy Github decided to pull some of the older commits into my PR for the map selector part that was merged earlier, but I guess the number of older commits that were pulled were not these many :\

**Comment by iCHAIT** [comment]
@tschuy Hi, I was wondering if anything in particular was preventing this PR from getting merged?

**Comment by tschuy** [comment]
Mostly that we haven't had time to review it. Since school is starting up again many of us took vacations and we've been slow to get back up to speed. I'll ping @Kennric about this again :)

**Comment by iCHAIT** [comment]
Oh , okay :+1:

**Comment by Kennric** [comment]
We currently have the develop branch (containing all these changes) deployed to our staging server, and have been waiting for feedback from the Sea Grant folks. When we get word back from them that things look ok, this will get a +1 from me to merge.

**Comment by iCHAIT** [comment]
Okay :)

**Comment by iCHAIT** [comment]
@Kennric Hi
I was wondering if there was any feedback from the guys at Sea Grant regarding any bug or anything that is not working correctly on the develop branch.

If there is any issue, I would like to work on it and fix it, my finals just got over and I have holidays of around 1 month starting in a few days. So I would like to work on the issues (if any).

Thanks :)

**Pull request merged**
