### PR TITLE
Feature request: show images in forms

### PR DESCRIPTION
**Pull request by sandeepmadaan**
For this issue : https://github.com/osu-cass/whats-fresh-api/issues/52
Please review it.

### CODE REVIEW

**Comment by tschuy** [comment]
Travis is still failing. The way we set it up, it runs not only the Django tests, but a flake8 linter as well. Flake8 checks for pep8 compliance (you can read about pep8 here: https://www.python.org/dev/peps/pep-0008/) -- essentially, whether the code fits the Python guide for clean coding.

You can install flake8 with pip and then run it, as shown below:

```
$ flake8 whats_fresh/
whats_fresh/whats_fresh_api/forms.py:38:34: E231 missing whitespace after ','
whats_fresh/whats_fresh_api/views/entry/products.py:80:43: E251 unexpected spaces around keyword / parameter equals
whats_fresh/whats_fresh_api/views/entry/products.py:81:30: E225 missing whitespace around operator
whats_fresh/whats_fresh_api/views/entry/products.py:91:43: E251 unexpected spaces around keyword / parameter equals
whats_fresh/whats_fresh_api/views/entry/products.py:92:30: E225 missing whitespace around operator
whats_fresh/whats_fresh_api/views/entry/products.py:93:1: W293 blank line contains whitespace
whats_fresh/whats_fresh_api/views/entry/products.py:136:20: E231 missing whitespace after ':'
whats_fresh/whats_fresh_api/views/entry/products.py:147:19: E231 missing whitespace after ':'
```

In addition, I noticed that it doesn't save the image successfully -- if it's set to Image A, I change it to Image B, and hit Save, if I browse back to the product, it doesn't have Image B, it still has Image A.

Looking at the diff, it looks like you're using a new "image_id" field in the request, replacing the old "image" request. Both of these just send an integer value -- we don't need to make a new "image_id" field of the form. That way, a whole bunch of the juggling you're doing from lines 45 to 93 are unnecessary. 

By including the image in the request as "image", it'll automatically make that a part of the product when we save the form to a specific product (line 83, ``save_instance(product_form, product)``) or create a new product from the form (line 85, ``product = Product.objects.create(**product_form.cleaned_data)``). We don't need to deal with getting any image objects, or assigning any to any products this way. Django handles it all automatically.

To include new commits, you don't need to create a new pull request. You can just push to the same branch that you used before, and it will automatically update this page to show the new commits, so we can keep all of the discussion in one place.

**Comment by sandeepmadaan** [comment]
Now Travis should have passed, both the flake8 and Django tests are working fine at my end. :(

Using the image_id from line 45 to 93 are required because like the "preparations", "image" field is also excluded from the ProductForm, so they need to requested and save individually. 

The saving of the image was working(I saw in the table) but on editing the product again, the image instance of the saved product was not called separately. So it looked like it did not save. Now I have changed the code and now it works perfectly fine.

Please review it again.

Thank you for all your precious feedback and help. :)

**Comment by tschuy** [comment]
Looks like there was a problem with the repositories we get our dependencies from when you pushed, which caused Travis to fail. I reran Travis and it succeeds.

It looks like you're modifying several of the test files. You shouldn't need to touch any of these if the code is working! Instead, use them to guide you as to what's broken. These were probably trying to tell you that the saving was broken, so if you've fixed that and they save successfully, you should be able to revert the tests back to what they were and have them all pass.

Regarding lines 45-93, you don't need to exclude images from the form. We're rendering each part of the form separately ({{ product_form.name }}, {{ product_form.image }}) instead of all together. To remove the image from what the user sees, you just need to remove the {{ product_form.image }} from the template, which you've done.

**Comment by sandeepmadaan** [comment]
Yes, now I have not excluded the image from ProductForm and it is working perfectly fine. Thank you.

I have reverted the tests too.

**Pull request closed without merging**
